In [49]:
import pandas as pd
from mtcnn import MTCNN
import cv2

In [26]:
name = 'COCO_train2014_000000023447.jpg'
name2 = 'frame_1ldes5388hcojdpr.jpg'
name3 = 'COCO_train2014_000000013143.jpg'
name4 = 'labelme_robvusmahjwfouq.jpg'

In [3]:
df = pd.read_csv('datasets/emotics_annotations_clean_v4.csv')

In [4]:
df.head()

,filename,folder,image_size,original_database,person,body_bbox,annotations_categories,annotations_continuous,gender,age,...,shape_y,x1,y1,x2,y2,valence,arousal,dominance,categories,n_cat
0,COCO_val2014_000000562243.jpg,mscoco/images,"(array([[640]], dtype=uint16), array([[640]], ...","(array(['mscoco'], dtype='<U6'), array([[(arra...","(array([[ 86, 58, 564, 628]], dtype=uint16), ...",[[ 86 58 564 628]],"(array([[array(['Disconnection'], dtype='<U13'...","(array([[5]], dtype=uint8), array([[3]], dtype...",Male,Adult,...,640.0,86.0,58.0,564.0,628.0,5.0,3.0,9.0,"Disconnection,Doubt/Confusion",2.0
1,COCO_train2014_000000288841.jpg,mscoco/images,"(array([[640]], dtype=uint16), array([[480]], ...","(array(['mscoco'], dtype='<U6'), array([[(arra...","(array([[485, 149, 605, 473]], dtype=uint16), ...",[[485 149 605 473]],"(array([[array(['Anticipation'], dtype='<U12')...","(array([[6]], dtype=uint8), array([[4]], dtype...",Male,Adult,...,480.0,485.0,149.0,605.0,473.0,6.0,4.0,7.0,Anticipation,1.0
2,COCO_val2014_000000558171.jpg,mscoco/images,"(array([[640]], dtype=uint16), array([[480]], ...","(array(['mscoco'], dtype='<U6'), array([[(arra...","(array([[305, 92, 461, 465]], dtype=uint16), ...",[[305 92 461 465]],"(array([[array(['Engagement'], dtype='<U10'),\...","(array([[7]], dtype=uint8), array([[8]], dtype...",Male,Teenager,...,480.0,305.0,92.0,461.0,465.0,7.0,8.0,8.0,"Engagement,Excitement,Happiness",3.0
3,COCO_train2014_000000369575.jpg,mscoco/images,"(array([[480]], dtype=uint16), array([[640]], ...","(array(['mscoco'], dtype='<U6'), array([[(arra...","(array([[221, 63, 448, 372]], dtype=uint16), ...",[[221 63 448 372]],"(array([[array(['Aversion'], dtype='<U8'),\n ...","(array([[8]], dtype=uint8), array([[9]], dtype...",Male,Kid,...,640.0,221.0,63.0,448.0,372.0,8.0,9.0,8.0,"Aversion,Pleasure",2.0
4,COCO_train2014_000000213009.jpg,mscoco/images,"(array([[500]], dtype=uint16), array([[333]], ...","(array(['mscoco'], dtype='<U6'), array([[(arra...","(array([[ 44, 143, 150, 288]], dtype=uint16), ...",[[ 44 143 150 288]],"(array([[array(['Confidence'], dtype='<U10'),\...","(array([[7]], dtype=uint8), array([[9]], dtype...",Male,Adult,...,333.0,44.0,143.0,150.0,288.0,7.0,9.0,10.0,"Confidence,Excitement",2.0

In [9]:
df[df.filename==name]

,filename,folder,image_size,original_database,person,body_bbox,annotations_categories,annotations_continuous,gender,age,...,shape_y,x1,y1,x2,y2,valence,arousal,dominance,categories,n_cat
6901,COCO_train2014_000000023447.jpg,mscoco/images,"(array([[640]], dtype=uint16), array([[413]], ...","(array(['mscoco'], dtype='<U6'), array([[(arra...","(array([[ 32, 63, 350, 398]], dtype=uint16), ...",[[ 32 63 350 398]],"(array([[array(['Fear'], dtype='<U4')]], dtype...","(array([[6]], dtype=uint8), array([[7]], dtype...",Male,Kid,...,413.0,32.0,63.0,350.0,398.0,6.0,7.0,7.0,Fear,1.0

In [11]:
df[df.filename==name2]

,filename,folder,image_size,original_database,person,body_bbox,annotations_categories,annotations_continuous,gender,age,...,shape_y,x1,y1,x2,y2,valence,arousal,dominance,categories,n_cat
3879,frame_1ldes5388hcojdpr.jpg,framesdb/images,"(array([[799]], dtype=uint16), array([[311]], ...","(array(['framesdb'], dtype='<U8'),)","(array([[701., 114., 798., 294.]], dtype=float...",[[701. 114. 798. 294.]],"(array([[array(['Engagement'], dtype='<U10'),\...","(array([[4]], dtype=uint8), array([[6]], dtype...",Male,Adult,...,311.0,701.0,114.0,798.0,294.0,4.0,6.0,7.0,"Engagement,Fatigue",2.0
3880,frame_1ldes5388hcojdpr.jpg,framesdb/images,"(array([[799]], dtype=uint16), array([[311]], ...","(array(['framesdb'], dtype='<U8'),)","(array([[ 65., 57., 250., 302.]], dtype=float...",[[ 65. 57. 250. 302.]],"(array([[array(['Engagement'], dtype='<U10'),\...","(array([[5]], dtype=uint8), array([[2]], dtype...",Male,Adult,...,311.0,65.0,57.0,250.0,302.0,5.0,2.0,8.0,"Engagement,Pleasure",2.0
3881,frame_1ldes5388hcojdpr.jpg,framesdb/images,"(array([[799]], dtype=uint16), array([[311]], ...","(array(['framesdb'], dtype='<U8'),)","(array([[224., 73., 322., 260.]], dtype=float...",[[224. 73. 322. 260.]],"(array([[array(['Engagement'], dtype='<U10')]]...","(array([[8]], dtype=uint8), array([[7]], dtype...",Female,Teenager,...,311.0,224.0,73.0,322.0,260.0,8.0,7.0,5.0,Engagement,1.0
3882,frame_1ldes5388hcojdpr.jpg,framesdb/images,"(array([[799]], dtype=uint16), array([[311]], ...","(array(['framesdb'], dtype='<U8'),)","(array([[505., 72., 601., 231.]], dtype=float...",[[505. 72. 601. 231.]],"(array([[array(['Engagement'], dtype='<U10'),\...","(array([[7]], dtype=uint8), array([[9]], dtype...",Female,Adult,...,311.0,505.0,72.0,601.0,231.0,7.0,9.0,6.0,"Engagement,Excitement,Happiness",3.0
3883,frame_1ldes5388hcojdpr.jpg,framesdb/images,"(array([[799]], dtype=uint16), array([[311]], ...","(array(['framesdb'], dtype='<U8'),)","(array([[557., 77., 656., 248.]], dtype=float...",[[557. 77. 656. 248.]],"(array([[array(['Engagement'], dtype='<U10')]]...","(array([[6]], dtype=uint8), array([[8]], dtype...",Female,Adult,...,311.0,557.0,77.0,656.0,248.0,6.0,8.0,7.0,Engagement,1.0

In [27]:
df[df.filename==name3]

Empty DataFrame
Columns: [filename, folder, image_size, original_database, person, body_bbox, annotations_categories, annotations_continuous, gender, age, shape_x, shape_y, x1, y1, x2, y2, valence, arousal, dominance, categories, n_cat]
Index: []

[0 rows x 21 columns]

In [19]:
df[df.filename==name4]

,filename,folder,image_size,original_database,person,body_bbox,annotations_categories,annotations_continuous,gender,age,...,shape_y,x1,y1,x2,y2,valence,arousal,dominance,categories,n_cat
17342,labelme_robvusmahjwfouq.jpg,ade20k/images,"(array([[2048]], dtype=uint16), array([[1536]]...","(array(['ade20k'], dtype='<U6'),)","(array([[1355, 791, 1739, 1400]], dtype=uint1...",[[1355 791 1739 1400]],"(array([[array(['Disconnection'], dtype='<U13'...","(array([[5]], dtype=uint8), array([[6]], dtype...",Male,Adult,...,1536.0,1355.0,791.0,1739.0,1400.0,5.0,6.0,7.0,"Disconnection,Fatigue",2.0

In [22]:
df.isna().sum()

filename                    0
folder                      0
image_size                  0
original_database           0
person                      0
body_bbox                   0
annotations_categories      0
annotations_continuous      0
gender                      0
age                         0
shape_x                     0
shape_y                     0
x1                          0
y1                          0
x2                          0
y2                          0
valence                   359
arousal                   359
dominance                 359
categories                  0
n_cat                       0
dtype: int64

In [25]:
df.groupby(df.folder).count()

,filename,image_size,original_database,person,body_bbox,annotations_categories,annotations_continuous,gender,age,shape_x,shape_y,x1,y1,x2,y2,valence,arousal,dominance,categories,n_cat
folder,,,,,,,,,,,,,,,,,,,,
ade20k/images,414,414,414,414,414,414,414,414,414,414,414,414,414,414,414,414,414,414,414,414
emodb_small/images,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311,1309,1309,1309,1311,1311
framesdb/images,7705,7705,7705,7705,7705,7705,7705,7705,7705,7705,7705,7705,7705,7705,7705,7348,7348,7348,7705,7705
mscoco/images,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276,14276

In [42]:
from os import listdir, getcwd
from os.path import isfile, join

In [31]:
detector = MTCNN()

In [32]:
def get_all_faces(img):
    results = detector.detect_faces(img)
    caras = []
    
    for i in results:
        # caja de la cara
        x, y, w, h = i['box']

        cara = img[y: y+h, x: x+w]
        
        caras.append(cara)
        
    return caras, results

In [33]:
def read_image(path):
    image = cv2.imread(path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    return image

In [36]:
def get_face_from_path(path):
    image = read_image(path)
    return get_all_faces(image)

In [47]:
bbox_df = pd.DataFrame()

In [35]:
folders = ['ade20k', 'emodb_small', 'framesdb', 'mscoco']

In [50]:
%time
for f in folders:
    print('Reading folder: ',f)
    abs_path = getcwd()
    abs_path = abs_path.replace('\\', '/')
    path = '/raw_data/EMOTIC_DATASET/emotic/' + f + '/images/'
    all_filenames = listdir(abs_path + path)
    for n in all_filenames:
        bboxs = get_face_from_path(abs_path + path + n)
        bbox_df = bbox_df.append(pd.DataFrame({'filename':n, 'bboxs': bboxs}))

Wall time: 0 ns
Reading folder:  ade20k
Reading folder:  emodb_small

ResourceExhaustedError:  OOM when allocating tensor with shape[1,4414,2946,10] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model_3/p_re_lu_12/Relu_1-0-0-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_predict_function_1782]

Function call stack:
predict_function

In [51]:
bbox_df.head()

,filename,bboxs
0,labelme_axxlfpyqbzhgkgf.jpg,"[[[[88 78 77], [90 80 81], [93 81 83], [94 82 ..."
1,labelme_axxlfpyqbzhgkgf.jpg,"[{'box': [2444, 655, 96, 131], 'confidence': 0..."
0,labelme_bftfwehzkyzhxvr.jpg,[]
1,labelme_bftfwehzkyzhxvr.jpg,[]
0,labelme_burfatorqtxrdsl.jpg,"[[[[107 98 103], [130 119 123], [116 104 106]..."